export const COPY = {
  empty: {
    noTasks: {
      title: "Belum ada tugas",
      description: "Tugas yang diberikan kepada Anda akan muncul di sini.",
    },
    noMatchingTasks: {
      title: "Tidak ada tugas yang cocok",
      description: "Coba ubah filter atau kata kunci pencarian Anda.",
    },
    noActiveTasks: {
      title: "Tidak ada tugas aktif",
      description: "Semua tugas Anda sudah selesai. Kerja bagus!",
    },
    allCaughtUp: {
      title: "Anda sudah menyelesaikan semua tugas",
      description: "Tidak ada tugas aktif saat ini. Cek lagi nanti.",
    },
    noNotifications: {
      title: "Belum ada notifikasi",
      description: "Notifikasi tugas akan muncul di sini.",
    },
    noTeamMembers: {
      title: "Belum ada anggota tim",
      description: "Tambahkan anggota tim untuk memulai.",
    },
    noLocations: {
      title: "Lokasi belum tersedia",
      description: "Aktifkan berbagi lokasi untuk muncul di radar.",
    },
    noFocOnMap: {
      title: "Tidak ada anggota FOC di radar",
      description: "Belum ada anggota FOC yang membagikan lokasinya.",
    },
    noMatchingMembers: {
      title: "Tidak ada anggota yang cocok",
      description: "Coba kata kunci pencarian lain.",
    },
  },
  loading: {
    tasks: "Memuat tugas...",
    users: "Memuat anggota tim...",
    map: "Memuat peta...",
    notifications: "Memuat notifikasi...",
    team: "Memuat data tim...",
    locations: "Memuat lokasi...",
  },
  time: {
    justNow: "Baru saja",
    minutesAgo: (m: number) => `${m} menit yang lalu`,
    hoursAgo: (h: number) => `${h} jam yang lalu`,
    daysAgo: (d: number) => `${d} hari yang lalu`,
    inMinutes: (m: number) => `Dalam ${m} menit`,
    inHours: (h: number) => `Dalam ${h} jam`,
    inDays: (d: number) => `Dalam ${d} hari`,
    overdueBy: (text: string) => `Terlambat ${text}`,
    dueToday: "Jatuh tempo hari ini",
    noDeadline: "Tanpa tenggat",
  },
  filters: {
    active: "Filter Aktif",
    clearAll: "Hapus semua",
    allStatus: "Semua status",
    allPriority: "Semua prioritas",
    allAssignees: "Semua penugasan",
    unassigned: "Belum ditugaskan",
  },
  tasks: {
    start: "Mulai",
    submitReview: "Sedang Ditinjau",
    complete: "Selesaikan",
    skipToNext: "Lewati ke berikutnya",
    overdue: "Terlambat",
  },
  search: {
    placeholder: "Cari tugas...",
    searching: "Mencari...",
  },
  actions: {
    retry: "Coba lagi",
    refresh: "Segarkan",
    back: "Kembali",
    cancel: "Batal",
    save: "Simpan",
    close: "Tutup",
    delete: "Hapus",
    edit: "Edit",
    deactivate: "Nonaktifkan",
    markAllRead: "Tandai semua dibaca",
  },
  nav: {
    dashboard: "Dasbor",
    radarMap: "Peta Radar",
    taskBoard: "Daftar Tugas",
    team: "Tim",
    settings: "Pengaturan",
    myTasks: "Tugas Saya",
    map: "Peta",
  },
  auth: {
    title: "TunetOps",
    subtitle: "Sistem Manajemen Operasi Jaringan",
    pinLabel: "Masukkan PIN",
    pinPlaceholder: "Masukkan PIN 4 digit Anda",
    signIn: "Masuk",
    signingIn: "Memproses...",
    welcome: (name: string) => `Selamat datang, ${name}!`,
    invalidPin: "PIN tidak valid. Silakan coba lagi.",
    contactAdmin: "Hubungi admin Anda untuk akses PIN",
  },
  pages: {
    admin: {
      title: "Dasbor Admin",
      subtitle: "Ringkasan operasi Tunet",
      totalTeam: "Total Tim",
      totalTasks: "Total Tugas",
      activeTasks: "Tugas Aktif",
      overdue: "Terlambat",
      teamMembers: "Anggota Tim",
      thisWeek: "Minggu ini",
    },
    team: {
      title: "Manajemen Tim",
      subtitle: "Tambah, edit, dan kelola anggota tim",
      addStaff: "Tambah Staf",
      addFirstStaff: "Tambah Staf Pertama",
      totalStaff: "Total Staf",
      active: "Aktif",
      inactive: "Tidak Aktif",
      allStaff: "Semua Staf",
      colName: "Nama",
      colRole: "Peran",
      colPhone: "Telepon",
      colPin: "PIN",
      colTelegram: "Telegram",
      colStatus: "Status",
      colActions: "Aksi",
      edit: "Edit",
      deactivate: "Nonaktifkan",
      deactivateOrDelete: "Nonaktifkan / Hapus",
      fullName: "Nama Lengkap",
      role: "Peran",
      phone: "Telepon",
      pinLabel: "PIN (4 digit)",
      telegramIdOptional: "ID Telegram (opsional)",
      addStaffForm: "Tambah Staf",
      editStaff: "Edit Staf",
      addNewMember: "Tambahkan anggota tim baru",
      updateMember: "Perbarui informasi anggota tim",
      saveChanges: "Simpan Perubahan",
      saving: "Menyimpan...",
      manageMember: "Kelola Anggota Tim",
      chooseHowToRemove: (name: string) =>
        `Pilih cara menghapus ${name} dari sistem.`,
      deactivateRecommended: "Nonaktifkan (Disarankan)",
      deactivateDescription:
        "Anggota tim tidak dapat masuk, tetapi data dan riwayat tugasnya tetap tersimpan.",
      deletePermanently: "Hapus Permanen",
      deleteDescription:
        "Tindakan ini akan menghapus semua data secara permanen. Tidak dapat dibatalkan.",
      cancel: "Batal",
      memberUpdated: (name: string) => `${name} diperbarui`,
      memberAdded: (name: string) => `${name} ditambahkan`,
      memberDeactivated: (name: string) => `${name} dinonaktifkan`,
      memberDeleted: (name: string) => `${name} dihapus permanen`,
      failedUpdateUser: "Gagal memperbarui pengguna",
      failedCreateUser: "Gagal membuat pengguna",
      failedDeactivate: "Gagal menonaktifkan pengguna",
      failedDelete: "Gagal menghapus pengguna",
      errorOccurred: "Terjadi kesalahan",
      requiredFields: "Nama, telepon, dan PIN wajib diisi",
      pinInvalid: "PIN harus tepat 4 digit",
    },
    noc: {
      title: "Dasbor NOC",
      subtitle: "Pusat Operasi Jaringan",
      active: "Aktif",
      overdue: "Terlambat",
      completed: "Selesai",
      total: "Total",
      recentTasks: "Tugas Terbaru",
    },
    foc: {
      title: "Tugas Saya",
      subtitle: "Pusat Operasi Lapangan",
      pending: (n: number) => `${n} menunggu`,
      activeTasks: "Tugas Aktif",
      completed: "Selesai",
      tasksCount: (n: number) => `${n} tugas`,
      taskCountOne: (n: number) => `${n} tugas`,
    },
    map: {
      title: "Peta Radar",
      subtitle: "Lokasi FOC & NOC secara real-time",
      back: "Kembali",
      legendActive: "Aktif",
      legendIdle: "Menganggur",
      legendOverdue: "Terlambat",
      legendRoute: "Rute",
      legendPing: "Ping",
      roleFoc: "FOC",
      roleNoc: "NOC",
      searchPlaceholder: "Cari anggota...",
      focCount: (n: number) => `FOC (${n})`,
      nocCount: (n: number) => `NOC (${n})`,
      inOffice: "Di Kantor",
      neverReported: "Belum pernah",
    },
    tasks: {
      title: "Daftar Tugas",
      subtitle: "Kelola semua tugas di seluruh tim",
      newTask: "Tugas Baru",
      viewKanban: "Tampilan Kanban",
      viewList: "Tampilan Daftar",
    },
    settings: {
      title: "Pengaturan",
      subtitle: "Kelola preferensi akun Anda",
      profile: "Profil",
      profileDesc: "Perbarui informasi pribadi Anda",
      appearance: "Tampilan",
      appearanceDesc: "Sesuaikan tampilan aplikasi",
      darkMode: "Mode Gelap",
      darkModeDesc: "Alihkan antara tema gelap dan terang",
      notifications: "Notifikasi",
      notificationsDesc: "Konfigurasikan preferensi notifikasi",
      taskAssignments: "Penugasan Tugas",
      taskAssignmentsDesc: "Dapatkan notifikasi saat tugas ditugaskan",
      statusUpdates: "Pembaruan Status",
      statusUpdatesDesc: "Dapatkan notifikasi saat status tugas berubah",
      overdueAlerts: "Peringatan Terlambat",
      overdueAlertsDesc: "Dapatkan notifikasi saat tugas terlambat",
      saveChanges: "Simpan Perubahan",
      saved: "Pengaturan disimpan!",
      name: "Nama",
      phone: "Telepon",
      role: "Peran",
    },
  },
  taskCard: {
    today: "Hari ini",
    oneDay: "1 hari",
    daysAgo: (n: number) => `${n} hari`,
    overdue: "Terlambat",
    assigned: "Ditugaskan",
    unassigned: "Belum Ditugaskan",
    start: "Mulai",
    submitReview: "Sedang Ditinjau",
    complete: "Selesai",
  },
  taskDetail: {
    title: "Detail dan riwayat tugas",
    description: "Deskripsi",
    assignee: "Penerima Tugas",
    createdBy: "Dibuat oleh",
    location: "Lokasi",
    deadline: "Tenggat",
    created: "Dibuat",
    updated: "Diperbarui",
    tags: "Tag",
    changeStatus: "Ubah Status",
    startWork: "Mulai Kerja",
    submitReview: "Sedang Ditinjau",
    markComplete: "Tandai Selesai",
    skipToNext: "Lewati ke Berikutnya",
    statusHistory: "Riwayat Status",
    loadingHistory: "Memuat riwayat...",
    noStatusChanges: "Belum ada perubahan status",
    statusChangedBy: (name: string, from: string, to: string) =>
      `${name} mengubah status dari ${from} ke ${to}`,
    movedTo: (status: string) => `Tugas dipindahkan ke ${status}`,
    failedUpdate: "Gagal memperbarui status tugas",
    priorityLabel: (priority: string) => `Prioritas ${priority}`,
    unassigned: "Belum Ditugaskan",
    unknown: "Tidak Diketahui",
    noDeadline: "Tanpa tenggat",
  },
  taskForm: {
    createTitle: "Buat Tugas Baru",
    createSubtitle: "Isi detail untuk membuat tugas baru",
    title: "Judul",
    description: "Deskripsi",
    priority: "Prioritas",
    assignTo: "Tugaskan ke",
    location: "Lokasi",
    deadline: "Tenggat",
    tags: "Tag",
    titlePlaceholder: "cth. Perbaikan Menara - Jl. Merdeka",
    descPlaceholder: "Jelaskan tugasnya...",
    locationPlaceholder: "cth. Jl. Merdeka No. 45, Kota Bandung",
    latitude: "Lintang",
    longitude: "Bujur",
    requiredFieldsMissing: "Harap isi semua kolom wajib",
    created: "Tugas berhasil dibuat!",
    failed: "Gagal membuat tugas",
    creating: "Membuat...",
    cancel: "Batal",
    create: "Buat Tugas",
  },
  taskList: {
    colTask: "Tugas",
    colStatus: "Status",
    colPriority: "Prioritas",
    colAssignee: "Penerima Tugas",
    colLocation: "Lokasi",
    colDeadline: "Tenggat",
    unassigned: "Belum Ditugaskan",
    overdue: "Terlambat",
    emptyMessage: "Tidak ada tugas yang cocok dengan filter saat ini",
  },
  notifications: {
    title: "Notifikasi",
    markAllRead: "Tandai semua dibaca",
    groups: {
      today: "Hari ini",
      yesterday: "Kemarin",
      earlier: "Sebelumnya",
    },
  },
  telegram: {
    welcomeWithUsername: (username: string) =>
      `👋 Selamat datang di TunetOps!\n\nSaya menemukan nama pengguna Anda: @${username}\n\nUntuk mulai membagikan lokasi Anda kepada tim:\n1. Ketuk 📎 (lampirkan)\n2. Pilih Lokasi\n3. Bagikan lokasi Anda saat ini\n\nAnda akan muncul di peta radar secara real-time!`,
    welcomeNoUsername: `👋 Selamat datang di TunetOps!\n\nSilakan atur nama pengguna Telegram di pengaturan Telegram Anda, lalu kirim /start lagi.`,
    welcomeWithPin: `👋 Selamat datang di TunetOps!\n\nUntuk menghubungkan akun Anda:\n1. Kirim PIN 4-digit Anda (contoh: 1234)\n2. Sistem akan otomatis mengikat akun Anda\n3. Anda akan menerima notifikasi tugas di sini\n\nBelum tahu PIN? Hubungi admin Anda.`,
    linked: (name: string) =>
      `✅ Terhubung ke TunetOps sebagai ${name}.\n\nAnda akan menerima notifikasi tugas di sini. Untuk share lokasi, tap 📎 → Location → Share.`,
    alreadyLinked: (name: string) =>
      `✅ Anda sudah terhubung ke TunetOps sebagai ${name}.\n\nKirim /help untuk melihat perintah yang tersedia.`,
    pinNotRecognized: `❌ PIN tidak dikenali. Silakan hubungi admin untuk PIN yang benar.`,
    help: `🤖 <b>Perintah Bot TunetOps</b>\n\n/start - Cek status koneksi\n/help - Tampilkan bantuan ini\n/tasks - Lihat tugas aktif Anda\n\n📍 Untuk share lokasi:\nTap 📎 → Location → Share\n\nLokasi Anda akan muncul di radar secara real-time.`,
    setUsernameFirst: "❌ Silakan atur nama pengguna Telegram terlebih dahulu.",
    noAccountFound: (username: string) =>
      `❌ Akun TunetOps tidak ditemukan untuk @${username}.\n\nMinta admin Anda untuk menambahkan nama pengguna Telegram ke profil staf Anda.`,
    noActiveTasks: "✅ Tidak ada tugas aktif. Anda sudah selesai semua!",
    activeTasksHeader: (n: number) => `📋 <b>Tugas Aktif Anda (${n})</b>\n\n`,
    tasksLocation: "📍 Lokasi:",
    tasksDeadline: "⏰ Tenggat:",
    statusLabel: (status: string) => `Status: ${status}`,
    locationReceivedTitle: "Lokasi Dikirim",
    locationReceivedMessage: (time: string) =>
      `Lokasi diperbarui via Telegram pada ${time}`,
    locationSendSuccess: (lat: number, lng: number) =>
      `✅ Lokasi terkirim!\n\n📍 ${lat.toFixed(6)}, ${lng.toFixed(6)}\n\nNOC sekarang bisa melihat Anda di radar.`,
    locationShared: (lat: number, lng: number) =>
      `✅ Lokasi dibagikan!\n\n📍 ${lat.toFixed(6)}, ${lng.toFixed(6)}\n\nNOC sekarang dapat melihat Anda di peta radar.`,
    locationUpdatedAt: (time: string) =>
      `Lokasi diperbarui melalui Telegram pada ${time}`,
    failedToSaveLocation: "❌ Gagal menyimpan lokasi. Silakan coba lagi.",
    fallback: (text: string) =>
      `Saya menerima: "${text}"\n\nKirim /help untuk melihat perintah yang tersedia.`,
    newTaskAssigned: "Tugas Baru Ditugaskan",
    priority: "Prioritas",
    location: "Lokasi",
    deadline: "Tenggat",
    shareLocationPrompt: "📍 Kirim lokasi Anda untuk membagikan posisi real-time Anda.",
  },
  toasts: {
    taskStatusUpdated: "Status tugas diperbarui!",
    taskStatusUpdateFailed: "Gagal memperbarui status tugas",
    geolocationUnsupported: "Geolocation tidak didukung",
    locationUpdated: "Lokasi diperbarui!",
    gettingLocation: "Mengambil lokasi Anda...",
    locationSharingEnabled: "Berbagi lokasi diaktifkan!",
    locationSharingDisabled: "Berbagi lokasi dinonaktifkan",
    geolocationDenied: "Izin lokasi ditolak. Aktifkan di pengaturan browser.",
  },
  statusBadge: {
    notSet: "Belum Diatur",
  },
  trend: {
    thisWeek: "Minggu ini",
    up: "Naik",
    down: "Turun",
    flat: "Stabil",
    noData: "Belum ada data",
  },
};
